### ISSUE TITLE
PyTango installation

### ISSUE THREAD

**Issue by ghost** [tango-controls/pytango#105]
Hi,

When I want to install PyTango this is what I get:

`Collecting pytango`
`Using cached pytango-9.2.1.tar.gz`
`Collecting fandango`
`Downloading fandango-12.6.1.tar.gz (244kB)`
`100% |████████████████████████████████| 245kB 2.1MB/s`
`Requirement already satisfied (use –upgrade to upgrade): six in /usr/lib/python3/dist-packages (from pytango)`
`Building wheels for collected packages: pytango, fandango`
`Running setup.py bdist_wheel for pytango … error`
`Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nwfsr2x3/pytango/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))"`
`bdist_wheel -d /tmp/tmpivmc62dgpip-wheel- –python-tag cp35:`
`Package omniORB4 was not found in the pkg-config search path.`
`Perhaps you should add the directory containing 'omniORB4.pc' to the PKG_CONFIG_PATH environment variable`
`No package 'omniORB4' found`
`Package libzmq was not found in the pkg-config search path.`
`Perhaps you should add the directory containing 'libzmq.pc' to the PKG_CONFIG_PATH environment variable`
`No package 'libzmq' found`
`Package tango was not found in the pkg-config search path.`
`Perhaps you should add the directory containing  'tango.pc' to the PKG_CONFIG_PATH environment variable`
`No package 'tango' found` 

even though I had defined PKG_CONFIG_PATH as

`PKG_CONFIG_PATH=/home/dusan/tangocs/tango-9.2.5a-gcc-5.4-gstabs+/lib/pkgconfig`

and in this folder are located all .pc files (omniORB4, libzmq, tango and log4tango).
How can I solve this problem?

Cheers,
Aratar

**Comment by andygotz** [comment]
Stupid question - have you exported PKG_CONFIG_PATH by doing:

`export PKG_CONFIG_PATH=/home/dusan/tangocs/tango-9.2.5a-gcc-5.4-gstabs+/lib/pkgconfig`

after you have defined and before running pip install pytango. See this site for more info:

https://askubuntu.com/questions/210210/pkg-config-path-environment-variable

Andy

**Comment by vxgmichel** [comment]
@Aratar93 What's your OS? On my linux mint 17 setup, those files are provided by the following packages:

    $ dpkg -S libzmq.pc
    libzmq3-dev:amd64: /usr/lib/x86_64-linux-gnu/pkgconfig/libzmq.pc
    $ dpkg -S omniORB4.pc
    libomniorb4-dev: /usr/lib/pkgconfig/omniORB4.pc
    $ dpkg -S tango.pc
    libtango8-dev:amd64: /usr/lib/x86_64-linux-gnu/pkgconfig/tango.pc

**Comment by ghost** [comment]
Hi guys,

Sorry for such a late response.

Andy,
> after you have defined

What do you mean with define?

I had exported PKG_CONFIG_PATH before I started installation of PyTango with
`echo export PKG_CONFIG_PATH=/home/$host/tangocs/tango-9.2.5a-gcc-5.4-gstabs+/lib/pkgconfig >> ~/.bashrc`
This is what I get from the terminal
`dusan@Dell:~$ echo $PKG_CONFIG_PATH`
`/home/dusan/tangocs/tango-9.2.5a-gcc-5.4-gstabs+/lib/pkgconfig`
so I guess this mean I exported well this environmental variable.

vxgmichel, 
I'm using Ubuntu 16.04 LTS. and I've installed Tango 9.2.5a from source code.
When I'm using **dpkg -S libzmq.pc** this is what I get
`dpkg-query: no path found matching pattern *libzmq.pc*`
What does this mean?

Many thanks,
Aratar

**Comment by ghost** [comment]
P.S. This is my bash file for installing PyTango. I'm not using any virtual enviroment, can that cause this kind of problem?

sudo apt install libboost1.58-dev libboost-python1.58-dev
sudo -H pip install setuptools
sudo -H pip install python_dateutil pytz cycler pyparsing Sphinx futures gevent numpy
sudo -H pip install pytango fandango

**Comment by andygotz** [comment]
Concerning PKG_CONFIG_PATH you can check that the directory you added contains the libzmq.pc file. If not then locate where this file is so you can add the directory to PKG_CONFIG_PATH.
You can check if pkg-config is finding zmq by typing "pkg-config --list-all | grep zmq"

I installed pytango today on Ubuntu 17.04 see this issue #107 . Maybe you can get some tips from this.

**Comment by vxgmichel** [comment]
@Aratar93 Try installing `libzmq3-dev` and `libomniorb4-dev` and check your environment using `env | grep PKG_CONFIG_PATH`.

**Comment by ghost** [comment]
This is what I get

`rile@Dell:~$ pkg-config --list-all | grep zmq`
`libzmq                         libzmq - 0MQ c++ library`

and

`rile@Dell:~$ env | grep PKG_CONFIG_PATH`
`PKG_CONFIG_PATH=/home/rile/tangocs/tango-9.2.5a-gcc-5.4-gstabs+/lib/pkgconfig`
so this is defined well. I also installed libzmq3-dev and libomniorb4-dev. But still, I'm not able to install pytango.

I read issue #107, and I've installed both libboost1.58-dev and libboost-python1.58-dev.
I also get this message (known error issue)

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Dm5cK9/pytango/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-q3mKaJ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-   Dm5cK9/pytango/

but right above this is what I also get

    /tmp/pip-build-Dm5cK9/pytango/ext/api_util.cpp:13:19: fatal error: tango.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Any ideas?

P.S. I am able to install PyTango from synaptic, but then I get version 8.

**Comment by ghost** [comment]
As for other commands from issue #107 this is what i get:

rile@Dell:~$ pip -V
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

rile@Dell:~$ apt search boost-python`
Sorting... Done`
Full Text Search... Done`
libboost-python-dev/xenial 1.58.0.1ubuntu1 amd64
   Boost.Python Library development files (default version)
libboost-python1.58-dev/xenial-updates,now 1.58.0+dfsg-5ubuntu3.1 amd64 [installed]
   Boost.Python Library development files
libboost-python1.58.0/xenial-updates,now 1.58.0+dfsg-5ubuntu3.1 amd64 [installed,automatic]
   Boost.Python Library

For **find /usr/lib -name libboost_python*** I get some very very long list.

rile@Dell:~$ dpkg -S boost_python
libboost-python1.58-dev: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
libboost-python1.58-dev: /usr/lib/x86_64-linux-gnu/libboost_python-py35.a
libboost-python1.58.0: /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
libboost-python1.58-dev: /usr/lib/x86_64-linux-gnu/libboost_python-py35.so
libboost-python1.58-dev: /usr/lib/x86_64-linux-gnu/libboost_python.so
libboost-python1.58-dev: /usr/lib/x86_64-linux-gnu/libboost_python-py27.a
libboost-python1.58.0: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.58.0
libboost-python1.58-dev: /usr/lib/x86_64-linux-gnu/libboost_python.a

**Comment by andygotz** [comment]
Your error with tango.h is because the libtango-dev package is not installed. Try:

` apt install libtango-dev`

**Comment by ghost** [comment]
rile@Dell:~$ sudo apt install libtango-dev
[sudo] password for rile: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libtango-dev

Is this the correct name of the library?

**Comment by ghost** [comment]
I have file tango.h in `rile@Dell:~/tangocs/tango-9.2.5a-gcc-5.4-gstabs+/include/tango`

**Comment by andygotz** [comment]
Strange the name is correct AFAICS.
Anyway you have tango.h from Tango 9.2.5a - this is even better because you need Tango 9 to install PyTango9. The fact that the build is not finding tango.h must be due to the pkg-config not finding tango. What do you get when you type this: 

`pkg-config --libs tango| grep tango`

**Comment by ghost** [comment]
rile@Dell:~$ pkg-config --libs tango| grep tango
-L/home/rile/tangocs/tango-9.2.5a-gcc-5.4-gstabs+/lib -ltango -lomniDynamic4 -lCOS4 -lomniORB4 -lomnithread -llog4tango -lzmq

**Comment by ghost** [comment]
`libzmq3-dev` and `libomniorb4-dev` helped me, now pytango can't find only **tango.pc**, but I don't know why I can't execute `sudo apt install libtango-dev`, I guess it will solve all my problems .

**Comment by LJBD** [comment]
@Aratar93 try running `pip install pytango` as root instead of with `sudo` (log onto root user with `su` - provided you know the password, of course).
I think there was an issue that environment variables were not passed to sudo. You can test that with `sudo echo $PKG_CONFIG_PATH` or `sudo pkg-config --libs tango| grep tango`. If you get any other output than without `sudo`, it would seem that my theory is correct.

**Comment by vxgmichel** [comment]
@LJBD @Aratar93 Or use [-E](https://unix.stackexchange.com/a/202389/217992) to preserve the environment:

    $ sudo -E pip install pytango # Or
    $ sudo PKG_CONFIG_PATH=... pip install pytango

**Comment by ghost** [comment]
Hi, guys


> If you get any other output than without sudo, it would seem that my theory is correct.

You are right, I have different outputs with and without sudo. Thank you for that!

When I enter **sudo -H pip install pytango** directly in the terminal, it is successfully installed. However, when I run this command from bash file I have problems displayed in my first post. Is it possible that bash file, when it is started, somehow don't see environmental variables while it is running?

Anyway, I took vxgmichel's advice and added -E to preserve environment variables, and now there is no error about missing .pc files (I run command from bash file btw), but I have this one:

`creating /tmp/pip-build-yUTnrz/pytango/build/sphinx`
`  creating /tmp/pip-build-yUTnrz/pytango/build/sphinx/doctrees`
`  creating /tmp/pip-build-yUTnrz/pytango/build/sphinx/html`
`  Running Sphinx v1.5.5`
  
`  Exception occurred:`
`   File "mock_tango_extension.py", line 28, in <module>`
`     from mock import MagicMock`
` ImportError: No module named mock`
`  The full traceback has been saved in /tmp/sphinx-err-8qS07M.log, if you want to report the issue to the developers.`
`  Please also report this if it was a user error, so that a better error message can be provided next time.`
`  A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!`

This I am seeing first time now. Any ideas how to solve this problem?

Thank you for your help,
Aratar

**Comment by ghost** [comment]
P.S. 

> Your error with tango.h is because the libtango-dev package is not installed. Try:
apt install libtango-dev

In my repository, only thing that I have and is similiar to this is libtango8-dev. But I suppose this is for older versions of Tango. Should I install it, even though I have Tango 9.2.5a?

**Comment by vxgmichel** [comment]
@Aratar93 You need the mock package to be able to build the documentation (`pip install mock`). However, this should be part of the build requirements, so I'll fix that. Could you confirm that this error prevent the installation from completing properly?

**Comment by vxgmichel** [comment]
> In my repository, only thing that I have and is similiar to this is libtango8-dev. But I suppose this is for older versions of Tango. Should I install it, even though I have Tango 9.2.5a?

You should use the development files corresponding to your install. So pointing to the tango sources with `PKG_CONFIG_PATH` is the right approach in your case.

**Comment by rile993** [comment]
Hi all. Situation is next. I added some libraries in the installation script. For python 3.5 I dont have any problems to install PyTango, but when I want to install it for Python 2.5 this is what I get:

`creating /tmp/pip-build-owmVjS/pytango/build/sphinx`
`  creating /tmp/pip-build-owmVjS/pytango/build/sphinx/doctrees`
`  creating /tmp/pip-build-owmVjS/pytango/build/sphinx/html`
`  Running Sphinx v1.6.1`
`  Mocking tango._tango extension module`

`  Exception occurred:`
`    File "/tmp/pip-build-owmVjS/pytango/build/lib.linux-x86_64-2.7/tango/__init__.py", line 123, in <module>`
`      from . import _tango`
`  ImportError: cannot import name _tango`
`  The full traceback has been saved in /tmp/sphinx-err-lUnaHo.log, if you want to report the issue to the developers.`
`  Please also report this if it was a user error, so that a better error message can be provided next ime.`
`  A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!`

I can't figure out which module is missing.
After that, setup.py for pytango is started again and then I have this error:

`/tmp/pip-build-Dm5cK9/pytango/ext/api_util.cpp:13:19: fatal error: tango.h: No such file or directory
compilation terminated.`
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
`I didnt't have this kind of problem eariler, and as I said, I installed PyTango for Python3. So you helped me to make progress. Do you have idea how I could solve this one?`

This is the error I already have eariler.
Then I installed libtango8-dev from the repository (I know I shouldn't, I wanted to see If this error is going to disappear). And after that, instead of the error that I'm missing tango.h file, this is what I'm getting:

`    /tmp/pip-build-B8OvzM/pytango/ext/attribute_info_ex.cpp:24:32: error: ‘memorized’ is not a member` `of ‘Tango::AttributeInfoEx {aka Tango::_AttributeInfoEx}’`
`      .def_readwrite("memorized",  &Tango::AttributeInfoEx::memorized)`
____________________________`^`
`    /tmp/pip-build-B8OvzM/pytango/ext/attribute_info_ex.cpp:25:34: error: ‘enum_labels’ is not a` `member of ‘Tango::AttributeInfoEx {aka Tango::_AttributeInfoEx}’`
`      .def_readwrite("enum_labels",  &Tango::AttributeInfoEx::enum_labels)`
_____________________________`^`
`    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

P.S. I posted this on site <https://github.com/sphinx-doc/sphinx/issues>, but they said 

> Sorry, this is issues for Sphinx. so we can't support tango package.
Could you ask it on thier project?

and that's why I am posting this problem here.

**Comment by rile993** [comment]
I hope I was clear. You helped me a lot till now, installation for python3.5 works, and there are fewer problems now for python 2.7. I apologize If I am a bit annoying, but this problem really drives me crazy.

**Comment by vxgmichel** [comment]
>  but when I want to install it for Python 2.5 this is what I get:

Do you mean python 2.7?

**Comment by rile993** [comment]
Yes, my mistake, sorry.

**Comment by vxgmichel** [comment]
I need a bit more information. Could you clone the pytango repo, run `python setup.py build` with your environment variables set correctly and provide me with the full output?

**Comment by vxgmichel** [comment]
I'm closing it, please re-open if necessary.
