### ISSUE TITLE
PyTango 8.1.9 tagged but not on PyPI

### ISSUE THREAD

**Issue by birkenfeld** [tango-controls/pytango#120]
Is this release stable and usable? If yes, please consider uploading it to PyPI. Thanks!

**Comment by vxgmichel** [comment]
It should be as stable and usable as v8.1.8 (more or less).

I don't think anyone is planning to support pytango8 so that's the reason why 8.1.9 has never been released on PyPI. @birkenfeld Do you thing it's worth it?

Also, note that it's possible to run:

    $ pip install git+https://github.com/tango-controls/pytango.git@v8.1.9

For the reference: [v8.1.9](https://github.com/tango-controls/pytango/releases/tag/v8.1.9)

**Comment by vxgmichel** [comment]
Closing it, please re-open if necessary.

**Comment by kobietaodkodu** [comment]
I think that it will be worth opening [PyTango 8.1.8+ Windows package needed #283](https://github.com/tango-controls/pytango/issues/283)
