### ISSUE TITLE
Stop exporting Tango Dev* types

### ISSUE THREAD

**Issue by grm84** [tango-controls/pytango#140]
Should we actually expose all the Tango::Dev* types (e.g. DevFloat, DevLong, etc)?
It would then force the use of pythonic types.
```python
from tango import DevFloat
from tango.server import Device, attribute


class PowerSupply(Device):

    @attribute(label='Deprecate this style', dtype=DevFloat)
    def voltage(self):
        return 1.0

    @attribute(label='Good attribute dtype ', dtype='float')
    def voltage(self):
        return 1.0
```

**Comment by vxgmichel** [comment]
One issue with not exposing the tango types is that it might break existing devices.

**Comment by LJBD** [comment]
Maybe we could add a deprecation warning for that? And make it obsolete in the future?

**Comment by johanfforsberg** [comment]
There might also be cases where you actually want to have a "DevFloat" attribute instead of "DevDouble" which I think is what you get when using "float", e.g. to follow the precision of the original data. I think it makes sense to keep them around, but we could hide them away a bit in the documentation.

**Comment by tiagocoutinho** [comment]
Just a detail concerning the number equivalence in pytango, tango and python data types :
`'float' == 'float64' == 'double' == float == DevDouble`
`'float32' == DevFloat`
