### ISSUE TITLE
Windows binaries download links

### ISSUE THREAD

**Issue by ldoyle** [tango-controls/pytango#218]
It is currently very hard to find working installers for windows.
http://www.tango-controls.org/ website points to github.com
github.com Readme points to readthedocs
readthedocs.com points to PyPI
pypi.com does not show any binaries anymore

On the Forum, I was pointed to https://ci.appveyor.com/project/NexeyaSGara/pytango
Until august, there were binaries there, however due to Appveyor deleting them currently none are available.
The only apparent current and long-term stable link is https://github.com/NexeyaSGara/pytango/releases
https://github.com/tango-controls/pytango/releases contains no binaries but also no mention of Sebastiens repo!

Suggested solution:
1. point pypi.com toward https://github.com/NexeyaSGara/pytango/releases for a "Windows install" section
2. additionally, point https://github.com/tango-controls/pytango/blob/develop/README.rst to same repo or update text to point to PyPI for binaries (which in turn points to above repo)
3. auto-upload binaries to releases section on github where they do not vanish 6months after build
4. as the long term solution, can the build be released on https://github.com/tango-controls/ instead of /NexeyaSGara ?

**Comment by vxgmichel** [comment]
Thanks for the report!

In my opinion, the official place to get the windows binaries should be PyPI:
https://pypi.org/project/PyTango#files

However, there is no official window release for versions `>9.2.1` yet:
https://pypi.org/project/PyTango/9.2.1/#files 

The builds for @NexeyaSGara are not official yet since PR #176 hasn't been merged. Once this work is done, we'll be able to build and release those binaries for current and future releases.

So my suggestion is: 

- [ ] Finish the work on #176.
- [ ] Add a section about binaries (windows exe, conda packages, etc.) in the readme
- [ ] Update the ["Installing" section](https://pytango.readthedocs.io/en/stable/start.html) of the documentation
- [ ] Make a new release and upload the binaries to pypi
- [ ] Investigate conda packaging on windows

**Comment by ldoyle** [comment]
Has there been any work done already in the direction of conda/pip packages?
I'm not an expert, but for me the best solution would seem a pip wheel distribution, if no one has looked into this I could give it a try. (If I understand correctly, this will allow us to go back to the simple "pip install pytango" in most environments.)

Depending on how long you think #176 will take to be completed I suggest putting the link
https://github.com/NexeyaSGara/pytango/releases
on PyPi as a temporary solution, it is really the only place right now for beginners to get a comprehensive collection of binaries (Py27-36, x86 and x64 each, great work by the way!) .
But having the official repo upload releases to PyPi seems best on the long term.
