### ISSUE TITLE
error put_property with a dict from a get_property

### ISSUE THREAD

**Issue by spierrejoz** [tango-controls/pytango#233]
Hello,
One python dev tried to do a put_property with as argument a dictionary coming from the get_property method, but it doesn’t work as you can see in the following example.
But if we call a put_property with a dictionary created in the program itself, it works.

```python
>>> dev2 = DeviceProxy("ANS/CA/MACHINESTATUS")
>>> prop = dev2.get_property('DiagProxies')
>>> prop
{'DiagProxies': ['XORBIT_RMS:ANS/DG/BPM-MANAGER/xOrbitRMSValue', 'ZORBIT_RMS:ANS/DG/BPM-MANAGER/zOrbitRMSValue', 'XORBIT_PEAK:ANS/DG/BPM-MANAGER/xOrbitPeakValue', 'ZORBIT_PEAK:ANS/DG/BPM-MANAGER/zOrbitPeakValue', 'EMITTANCE_H:ANS-C02/DG/PHC-EMIT/EmittanceH', 'EMITTANCE_V:ANS-C02/DG/PHC-EMIT/EmittanceV']}
>>> prop = dev2.put_property(prop)
>>> prop = dev2.get_property('DiagProxies')
>>> prop
{'DiagProxies': ["['XORBIT_RMS:ANS/DG/BPM-MANAGER/xOrbitRMSValue', 'ZORBIT_RMS:ANS/DG/BPM-MANAGER/zOrbitRMSValue', 'XORBIT_PEAK:ANS/DG/BPM-MANAGER/xOrbitPeakValue', 'ZORBIT_PEAK:ANS/DG/BPM-MANAGER/zOrbitPeakValue', 'EMITTANCE_H:ANS-C02/DG/PHC-EMIT/EmittanceH', 'EMITTANCE_V:ANS-C02/DG/PHC-EMIT/EmittanceV']"]}
>>>
```
Regards,
Sandra PIERRE-JOSEPH ZEPHIR

**Comment by alainbuteau** [comment]
Raynald
I assign the ticket to you as I do not clearly know who will do the jobs

**Comment by bourtemb** [comment]
Dear @alainbuteau ,
I will unassign this ticket since I am sure I won't do this job and it could be confusing because some people might think I am actually taking care of it...
I let the PyTango team manage their issues the way they are used to.
When looking at the other PyTango issues, I can see none of them is actually assigned so I guess this is done on purpose.
If you want to raise the priority of an issue, you can raise it during a Tango kernel teleconf meeting or comment the tickets of course.

**Comment by vxgmichel** [comment]
@alainbuteau @spierrejoz 

This issue has been [fixed](https://github.com/tango-controls/pytango/pull/27/commits/ed0bf9096674b4d3f8601db7b7323c8381cf641b) in version [9.2.0](https://github.com/tango-controls/pytango/commit/62e0b32e2ee63d78c1e6147898ae6f6dad499f73). 

Also, pytango 8 is not maintained anymore. Please upgrade to pytango [9.2.5](https://github.com/tango-controls/pytango/releases/tag/v9.2.5).
