### ISSUE TITLE
Wrong data type conversion - 'int' to DevLong or DevLong64

### ISSUE THREAD

**Issue by dmiego** [tango-controls/pytango#282]
Hello.

When I create a class using Pogo and specify the type of an attribute as "DevLong", Pogo generates dtype='int'. It's OK, according to the table of equivalences in the documentation.
But when I was testing the DS from "Test Device" in Jive, I've noticed that 'int' converts to the DevLong64.

So I've created test server to test if any other types are not converting right.
- int -> DevLong64
- 'int' -> DevLong64
- 'uint' -> DevULong64

There is the same situation for the spectrum attributes.

![1561984800524](https://user-images.githubusercontent.com/13482645/60438279-ff6d1d80-9c18-11e9-8047-b8c50d5e775e.png)
![1561985094323](https://user-images.githubusercontent.com/13482645/60438285-01cf7780-9c19-11e9-92ed-882de3ff8153.png)

There is no such problem with float and double attributes.

**Comment by ajoubertza** [comment]
Hi @Diego91RA.  Yes, you have noticed something interesting.  Thanks for the nice screenshots.

From what I can see in the git history:
- PyTango < v8.1.8 was interpreting `dtype='int'` and `dtype=int` as `DevLong`.
- PyTango [v8.1.8 to  < v9.2.0](https://github.com/tango-controls/pytango/commit/e44430434a44a2db3deb661f30ac8fc8e6c5679c) there was inconsistency - `dtype='int'` was `DevLong`, but `dtype=int` was `DevLong64`.
- Since [v9.2.0](https://github.com/tango-controls/pytango/commit/73ef1d3592e33e687289cd852de9703196f1e8e4), both `dtype='int'` and `dtype=int` are `DevLong64`.
(Code has since been centralised [here](https://github.com/tango-controls/pytango/blob/c32eb6ac374a9c27ecaa5780392194b491a6f9f5/tango/utils.py#L122)).

The table of equivalence in [our docs](https://pytango.readthedocs.io/en/stable/server_api/server.html) was not updated, and neither was Pogo.

The [IDL](https://github.com/tango-controls/tango-idl/blob/03e0e74783f68231dee55935dff7a3ad1abeb195/tango.idl#L42) maps `DevLong` to the IDL `long` type, which is a signed 32-bit number (if I understand the spec, correctly).

I think we could go with one of these options:
1. Change PyTango docs so `'int'` and `int` map to `DevLong64`.  And change Pogo so that `DevLong` maps to `'int32'` instead of `'int'`.
2.  Change PyTango implementation so that `'int'` and `int` map to `DevLong` again, instead of `DevLong64`.

I prefer option 1 - it seems less likely to cause compatibility issues with existing PyTango device servers in production.  The 64-bit integer behaviour of PyTango has been this way since at least August 2016 (v9.2.0), so users are probably expecting it.

@tiagocoutinho, @andygotz, @sergirubio, and other PyTango contributors:  any comments, what do you think is the best way forward?

**Comment by dmiego** [comment]
Hi @ajoubertza.

For me there is no big difference between 1 and 2 option.
I just wanted you to know that something works not the way it was documented.

Actually Pogo lacks many PythonHL features, which are mentioned in the issues in Pogo repo. From new style import of pytango module to polling and things like wrong type conversion.
These bugs are not so dramatic for experienced users (they can write code by themselves, without Pogo), but it may be confusing for beginners.

**Comment by andygotz** [comment]
This could be a good time to complete the Pogo PythonHL templates to support all features of PythonHL. Who could make a list of the missing features?

**Comment by ajoubertza** [comment]
@andygotz SKA should be looking at Pogo PythonHL templates "soonish" (not before September, 2019).

Since no one has any strong opinions on the options I've proposed.  I'm going with option 1:

> 1. Change PyTango docs so `'int'` and `int` map to `DevLong64`. And change Pogo so that DevLong maps to `'int32'` instead of `'int'`.

For now, just doing changes in PyTango.
