### ISSUE TITLE
PyTango 8.1.8+ Windows package needed

### ISSUE THREAD

**Issue by AleksanderStanikPV** [tango-controls/pytango#283]
We are struggling with memory leaks in PyTango 8.1.6 when using commands with an array attribute. We tried to install  from pip (PyTango 8.1.8, 8.1.9) in which it seems that problem has been fixed. But we have a problem with pip install:
pip install git+https://github.com/tango-controls/pytango.git@v8.1.8
...
error: option --single-version-externally-managed not recognized
...

Maybe someone has last ready-to-use Windows PyTango8.1.8+ package ?
Any help would be welcome

**Comment by andygotz** [comment]
Hi @AleksanderStanikPV, some additonal info:  as you know we have CI for the LTS version of Tango 9 for Windows. This depends on using cmake for compiling Windows. I am not sure how much work it is to make cmake work for Tango 8 on Windows. If you (or someone else) does not manage then the only option is to recompile Tango 8.1.8 and PyTango manually using Visual Studio. 

The experts can correct me or tell you how much work it is to adapt cmake for Tango 8.

**Comment by ajoubertza** [comment]
> The experts can correct me or tell you how much work it is to adapt cmake for Tango 8.

I'm not an expert on Windows builds, but looking at the cmake and appveyor files we are using for Windows V9 builds, it won't be that easy.  A few issues:
- getting the correct Windows builds of the cppTango and Boost libraries.  
- small changes to the PyTango cpp code may be required to get compilation working (we needed this for V9).

Can anyone remember where the 8.1.6 Windows builds on PyPI came from?

**Comment by mliszcz** [comment]
Hi @AleksanderStanikPV,

> We are struggling with memory leaks in PyTango 8.1.6 when using commands with an array attribute. We tried to install from pip (PyTango 8.1.8, 8.1.9) in which it seems that problem has been fixed.

I confirm, below code increases server's VmRSS by ~6MB on each run on 8.1.6. The problem is not visible in 8.1.8:
```python
# server
    @command(
        dtype_in=['int'],
        dtype_out='DevVarUShortArray')
    def NumberListCommand(self, value):
# clilent
for i in xrange(100000): dp.NumberListCommand([1,2,3,4,5])
```

> But we have a problem with pip install:
pip install git+https://github.com/tango-controls/pytango.git@v8.1.8
...
error: option --single-version-externally-managed not recognized
...

This is because PyTango 8.x is still using distutils which does not support this option. As a workaround, you can try installing as egg or checkout the source tree and manually run `setup.py`.

```
pip install --egg pytango==8.1.8
easy_install pytango==8.1.8
```

**Comment by tiagocoutinho** [comment]
Hi @AleksanderStanikPV,

Would you consider using 9.3.1dev1?

It should be API compatible with any pytango servers/clients you have running.
Since PyTango is statically compiled with its own version of Tango C++, you can even have installed the tango 8 windows package and the pytango 9 together in the same machine. They don't interfere.

It is available for windows on pypi.
It is a pre-release so you must install it with:
`pip install --pre pytango`
