### ISSUE TITLE
Server green mode

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/pytango#333]
Hi,
According to docs, TANGO server GreenMode is currently in beta version. Is there any plan to provide stable version of TANGO Device Server GreenMode?

**Comment by ajoubertza** [comment]
Hi @stanislaw55.
No immediate plans, sorry.  Do you know of features that are missing or functionality that is broken (other than #173)?  If we did any further work, I propose that the `Asyncio` mode is prioritised `Gevent`.

**Comment by andygotz** [comment]
Hi @stanislaw55,
the Green mode is used heavily at the ESRF (we have a number of gevent based applications) and is in production. I do not know why the documentation still says it is in beta. The asyncio mode is also used in production by some sites e.g. MAXIV. Maybe @tiagocoutinho and @vxgmichel can say something about what the status of the Green mode is.
Have you noticed something missing? 
Who else is using the Green mode?

**Comment by vxgmichel** [comment]
This addition to the docs was made 3 years ago (https://github.com/tango-controls/pytango/commit/ef62a236a366144f38d7305a3da0341f056e4ff5), it may be time to get rid of it :)

The one point that comes to mind is @tiagocoutinho telling me about race conditions in tango when the monitor lock is disabled. If those haven't been fixed, I guess it would justify calling server green mode "experimental" (the word "beta" doesn't appear in the docs by the way).

Also, I think there are a few mistakes in [this page](https://pytango.readthedocs.io/en/stable/green_modes/green.html):

> [About gevent green mode] Another thing to have in mind is that the Tango monitor lock is present - you can’t have two read operations happening concurrently. Any subsequent ones will always have to wait for the first one to finish.

As far as I remember this is not true. The monitor lock is disabled for both the gevent and the asyncio green mode:

https://github.com/tango-controls/pytango/blob/5865b6f0a53f2264df1d1443147b2e34b7399fc5/tango/server.py#L1333-L1334

This has been the case since 2015: https://github.com/tango-controls/pytango/commit/803b7e9939e6477f9d736a294d7360a052922da6

Another mistake in the docs:

> [About the asyncio green mode ]It’s especially useful if you want to perform some long operations and don’t want to prevent clients from accessing other parts of your device (attributes, in particular). This means that in Asyncio green mode there is no monitor lock!

... but then proceeds with an example of a command spawning a background task and returning immediately:
```python
    @command
    async def long_running_command(self):
        loop = asyncio.get_event_loop()
        future = loop.create_task(self.coroutine_target())
```

Also, hi guys :)

**Comment by ajoubertza** [comment]
Hi @vxgmichel :)

Thanks for the details (and the long memory).  I've made a draft PR in the meantime.  I'd appreciate if you'd have a look to see if I understand you correctly.

The removal of the "experimental" tag is pending @tiagocoutinho's response on the race conditions.

**Comment by stanislaw55** [comment]
Hi @ajoubertza, 
I had no idea that docs are outdated. It's good to see PR with an update ;)

Hi @andygotz 
Great to here that Server GreenMode is used at production at ESRF. That makes me think there was just something broken with my setup. I will investigate further in #173.

When #334 is merged, I think this issue can be closed.
