### ISSUE TITLE
Conda package with support for Python3.8

### ISSUE THREAD

**Issue by kif** [tango-controls/pytango#346]
Hi,
I tried to do a conda-install of PyTango and apparently there is no build of it ...
Do you confirm ? Is there a bug or is it just a lack of packaging ?

Cheers & take care.

Jerome

**Comment by ajoubertza** [comment]
Hi @kif 

I confirm it is due to a missing Conda packages.  We haven't made any for Python 3.8 yet.

There's WIP PR #344 to get PyTango tested against 3.8 - I don't expect any changes to be required, but yet to be confirmed, due to the Conda issue with the cppTango and dependent packages (we use Conda for the CI).

We are also moving the Conda builds to Github, but that is also still in progress.
https://github.com/tango-controls/tango-conda-recipes
https://github.com/tango-controls/pytango-conda-recipes
https://github.com/tango-controls/pytango-windows-conda-recipes

**Comment by bourtemb** [comment]
@kif, pytango 9.3.2 conda package for python 3.8 is now available on tango-controls conda channel.
